name: AI Code Review with Deepseek
description: Uses Deepseek to review PR code

inputs:
  token:
    required: true
  deepseek_api_key:
    required: true
  pr_number:
    required: true
  owner:
    required: true
  repo:
    required: true

runs:
  using: 'node20'
  main: 'index.js'
